# Generated by Django 3.2.5 on 2021-07-04 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kcal', models.FloatField()),
                ('fat', models.FloatField()),
                ('saturates', models.FloatField()),
                ('carbs', models.FloatField()),
                ('sugars', models.FloatField()),
                ('fibre', models.FloatField()),
                ('protein', models.FloatField()),
                ('salt', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='FoodGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/foods')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.food')),
            ],
        ),
    ]
