# Generated by Django 3.2.5 on 2021-07-05 04:19

from django.db import migrations, models
import righteous.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210705_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to=righteous.utils.rename_imagefile_to_uuid),
        ),
    ]
