# Generated by Django 3.2.5 on 2021-07-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(max_length=255, upload_to='media/foods/<function rename_imagefile_to_uuid at 0x00000198608E4310>'),
        ),
    ]
