# Generated by Django 3.2.5 on 2021-07-05 09:24

from django.db import migrations, models
import righteous.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(max_length=255, upload_to=righteous.utils.rename_imagefile_to_uuid),
        ),
    ]
